extern int Light_SalmonR, Light_SalmonG, Light_SalmonB;
extern int CoralR, CoralG, CoralB;
extern int TomatoR, TomatoG, TomatoB;
extern int Orange_RedR, Orange_RedG, Orange_RedB;
extern int Dark_OrangeR, Dark_OrangeG, Dark_OrangeB;
extern int OrangeR, OrangeG, OrangeB;
extern int Deep_SaffronR, Deep_SaffronG, Deep_SaffronB;
extern int Light_ApricotR, Light_ApricotG, Light_ApricotB;
extern int SaffronR, SaffronG, SaffronB;
extern int SunglowR, SunglowG , SunglowB;
extern int GoldenR, GoldenG , GoldenB;
extern int Light_GoldenR, Light_GoldenG , Light_GoldenB;
extern int Peach_PuffR, Peach_PuffG , Peach_PuffB;
extern int MoccasinR, MoccasinG , MoccasinB;
extern int Papaya_WhipR, Papaya_WhipG , Papaya_WhipB;
extern int SalmonR, SalmonG , SalmonB;
extern int Vivid_Orange_PeelR, Vivid_Orange_PeelG , Vivid_Orange_PeelB;
extern int Fire_OpalR , Fire_OpalG  , Fire_OpalB;
extern int BlushR , BlushG  , BlushB;
extern int Sandy_BrownR , Sandy_BrownG , Sandy_BrownB;
extern int SiennaR , SiennaG , SiennaB;
extern int ChocolateR , ChocolateG , ChocolateB;
extern int PeruR , PeruG , PeruB;
extern int Sienna_DarkR , Sienna_DarkG  , Sienna_DarkB;
extern int Saddle_BrownR , Saddle_BrownG  , Saddle_BrownB;
extern int Sandy_Brown_LightR , Sandy_Brown_LightG , Sandy_Brown_LightB;
extern int Chocolate_DarkR , Chocolate_DarkG , Chocolate_DarkB;
//File dei colori utilizzati per distinguere i distretti in Mod. Colore Normale nella Zona  .
